### ISSUE TITLE
Can't run the requirements.txt

### ISSUE THREAD

**Issue by yuzhou2333** [OrangeInSouth/Pareto-Mutual-Distillation#1]
In this section,
-e git+https://git.pcl.ac.cn/ychuang/Mutual-Distillation.git@3b97956c34a2ba6ff49d71fc310a578aa03f6dab#egg=fairseq
i sign in the website
it said that he will send email in three hours,but can't receive the emial to valid it.

**Comment by OrangeInSouth** [comment]
Hi, please delete this line of dependency in the requirements.txt.

I have updated the requirements.txt, thanks!

**Comment by yuzhou2333** [comment]
> Hi, please delete this line of dependency in the requirements.txt.
> 
> I have updated the requirements.txt, thanks!

That's really nice,Thank you very much~~
