### ISSUE TITLE
Runing Time And The Application In Other Fields

### ISSUE THREAD

**Issue by yuzhou2333** [OrangeInSouth/Pareto-Mutual-Distillation#2]
Dear Author, How long have you been running with 16 V100s? And have you tried to use simple models to verify the effect in other fields?

**Comment by OrangeInSouth** [comment]
Hi, we spent 55 hours in the many-to-one translation setting.

We have yet validated our method on other fields.

**Comment by yuzhou2333** [comment]
> Hi, we spent 55 hours in the many-to-one translation setting.
> 
> We have yet validated our method on other fields.
作者您好，我想要把这篇论文的自适应蒸馏策略应用到其他领域，现在遇到了一些问题，可以加一下您的微信讨论一下吗？

**Comment by OrangeInSouth** [comment]
哦哦好滴，可以把你微信号发邮件给我：ychuang@ir.hit.edu.cn
